// Code generated by genji.
// DO NOT EDIT!

package genji_test

import (
	"errors"

	"github.com/asdine/genji/record"
)

// GetField implements the field method of the record.Record interface.
func (u *User) GetField(name string) (record.Field, error) {
	switch name {
	case "id":
		return record.NewInt64Field("id", u.ID), nil
	case "name":
		return record.NewStringField("name", u.Name), nil
	case "age":
		return record.NewUint32Field("age", u.Age), nil
	}

	return record.Field{}, errors.New("unknown field")
}

// Iterate through all the fields one by one and pass each of them to the given function.
// It the given function returns an error, the iteration is interrupted.
func (u *User) Iterate(fn func(record.Field) error) error {
	var err error

	err = fn(record.NewInt64Field("id", u.ID))
	if err != nil {
		return err
	}

	err = fn(record.NewStringField("name", u.Name))
	if err != nil {
		return err
	}

	err = fn(record.NewUint32Field("age", u.Age))
	if err != nil {
		return err
	}

	return nil
}

// ScanRecord extracts fields from record and assigns them to the struct fields.
// It implements the record.Scanner interface.
func (u *User) ScanRecord(rec record.Record) error {
	return rec.Iterate(func(f record.Field) error {
		var err error

		switch f.Name {
		case "id":
			u.ID, err = f.DecodeToInt64()
		case "name":
			u.Name, err = f.DecodeToString()
		case "age":
			u.Age, err = f.DecodeToUint32()
		}
		return err
	})
}

// Scan extracts fields from src and assigns them to the struct fields.
// It implements the driver.Scanner interface.
func (u *User) Scan(src interface{}) error {
	rr, ok := src.(record.Record)
	if !ok {
		return errors.New("unable to scan record from src")
	}

	return u.ScanRecord(rr)
}
