package testdata

// Basic is the simplest struct that can be used with Genji: No tags, no methods, no comments.
// This must not be generated by the generator.
type Basic struct {
	A    string
	B    int64
	C, D int64
}
