package testdata

// Basic is the simplest struct that can be used with Genji: No tags, no methods, no comments.
// This must not be generated by the generator.
type Basic struct {
	A    string
	B    int64
	C, D int64
}

// basic is like Basic except that it is unexported.
type basic struct {
	A    string
	B    int64
	C, D int64
}

// Pk is a struct that selects its own primary key.
// This must not be generated by the generator.
type Pk struct {
	A string
	B int64 `genji:"pk"`
}

// Indexed is a struct that declares a indexed fields.
// This must not be generated by the generator.
type Indexed struct {
	A string `genji:"index"`
	B int64
}

// Sample will hold one row of the result of a query
type Sample struct {
	A string
	B int64
}
