//go:build !noasm && darwin && arm64
// AUTO-GENERATED BY GOCC -- DO NOT EDIT

package column

import "unsafe"

//go:noescape,nosplit
func int64_add_scalar(a unsafe.Pointer, b int64, result unsafe.Pointer, len int32)

//go:noescape,nosplit
func int64_sub_scalar(a unsafe.Pointer, b int64, result unsafe.Pointer, len int32)

//go:noescape,nosplit
func int64_mul_scalar(a unsafe.Pointer, b int64, result unsafe.Pointer, len int32)

//go:noescape,nosplit
func int64_div_scalar(a unsafe.Pointer, b int64, result unsafe.Pointer, len int32)

//go:noescape,nosplit
func int64_mod_scalar(a unsafe.Pointer, b int64, result unsafe.Pointer, len int32)

//go:noescape,nosplit
func int32_add_scalar(a unsafe.Pointer, b int32, result unsafe.Pointer, len int32)

//go:noescape,nosplit
func int32_sub_scalar(a unsafe.Pointer, b int32, result unsafe.Pointer, len int32)

//go:noescape,nosplit
func int32_mul_scalar(a unsafe.Pointer, b int32, result unsafe.Pointer, len int32)

//go:noescape,nosplit
func int32_div_scalar(a unsafe.Pointer, b int32, result unsafe.Pointer, len int32)

//go:noescape,nosplit
func int32_mod_scalar(a unsafe.Pointer, b int32, result unsafe.Pointer, len int32)
