// Code generated by pigeon; DO NOT EDIT.

package parser

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"io/ioutil"
	"math"
	"os"
	"sort"
	"strconv"
	"strings"
	"unicode"
	"unicode/utf8"

	"github.com/asdine/genji/field"
	"github.com/asdine/genji/query"
)

var g = &grammar{
	rules: []*rule{
		{
			name: "Input",
			pos:  position{line: 5, col: 1, offset: 24},
			expr: &actionExpr{
				pos: position{line: 5, col: 10, offset: 33},
				run: (*parser).callonInput1,
				expr: &seqExpr{
					pos: position{line: 5, col: 10, offset: 33},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 5, col: 10, offset: 33},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 5, col: 12, offset: 35},
							label: "stmt",
							expr: &ruleRefExpr{
								pos:  position{line: 5, col: 17, offset: 40},
								name: "Statement",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 5, col: 27, offset: 50},
							name: "_",
						},
						&ruleRefExpr{
							pos:  position{line: 5, col: 29, offset: 52},
							name: "EOF",
						},
					},
				},
			},
		},
		{
			name: "Statement",
			pos:  position{line: 9, col: 1, offset: 82},
			expr: &actionExpr{
				pos: position{line: 9, col: 14, offset: 95},
				run: (*parser).callonStatement1,
				expr: &seqExpr{
					pos: position{line: 9, col: 14, offset: 95},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 9, col: 14, offset: 95},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 9, col: 16, offset: 97},
							label: "selectStmt",
							expr: &ruleRefExpr{
								pos:  position{line: 9, col: 27, offset: 108},
								name: "SelectStmt",
							},
						},
					},
				},
			},
		},
		{
			name: "Integer",
			pos:  position{line: 17, col: 1, offset: 171},
			expr: &choiceExpr{
				pos: position{line: 17, col: 11, offset: 183},
				alternatives: []interface{}{
					&litMatcher{
						pos:        position{line: 17, col: 11, offset: 183},
						val:        "0",
						ignoreCase: false,
					},
					&seqExpr{
						pos: position{line: 17, col: 17, offset: 189},
						exprs: []interface{}{
							&ruleRefExpr{
								pos:  position{line: 17, col: 17, offset: 189},
								name: "NonZeroDecimalDigit",
							},
							&zeroOrMoreExpr{
								pos: position{line: 17, col: 37, offset: 209},
								expr: &ruleRefExpr{
									pos:  position{line: 17, col: 37, offset: 209},
									name: "DecimalDigit",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "DecimalDigit",
			pos:  position{line: 19, col: 1, offset: 224},
			expr: &charClassMatcher{
				pos:        position{line: 19, col: 16, offset: 241},
				val:        "[0-9]",
				ranges:     []rune{'0', '9'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "NonZeroDecimalDigit",
			pos:  position{line: 21, col: 1, offset: 248},
			expr: &charClassMatcher{
				pos:        position{line: 21, col: 23, offset: 272},
				val:        "[1-9]",
				ranges:     []rune{'1', '9'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "Exponent",
			pos:  position{line: 23, col: 1, offset: 279},
			expr: &seqExpr{
				pos: position{line: 23, col: 12, offset: 292},
				exprs: []interface{}{
					&litMatcher{
						pos:        position{line: 23, col: 12, offset: 292},
						val:        "e",
						ignoreCase: true,
					},
					&zeroOrOneExpr{
						pos: position{line: 23, col: 17, offset: 297},
						expr: &charClassMatcher{
							pos:        position{line: 23, col: 17, offset: 297},
							val:        "[+-]",
							chars:      []rune{'+', '-'},
							ignoreCase: false,
							inverted:   false,
						},
					},
					&oneOrMoreExpr{
						pos: position{line: 23, col: 23, offset: 303},
						expr: &ruleRefExpr{
							pos:  position{line: 23, col: 23, offset: 303},
							name: "DecimalDigit",
						},
					},
				},
			},
		},
		{
			name: "Word",
			pos:  position{line: 25, col: 1, offset: 318},
			expr: &actionExpr{
				pos: position{line: 25, col: 9, offset: 326},
				run: (*parser).callonWord1,
				expr: &seqExpr{
					pos: position{line: 25, col: 9, offset: 326},
					exprs: []interface{}{
						&oneOrMoreExpr{
							pos: position{line: 25, col: 9, offset: 326},
							expr: &choiceExpr{
								pos: position{line: 25, col: 10, offset: 327},
								alternatives: []interface{}{
									&ruleRefExpr{
										pos:  position{line: 25, col: 10, offset: 327},
										name: "EnglishChar",
									},
									&ruleRefExpr{
										pos:  position{line: 25, col: 24, offset: 341},
										name: "UnicodeChar",
									},
								},
							},
						},
						&zeroOrMoreExpr{
							pos: position{line: 25, col: 38, offset: 355},
							expr: &choiceExpr{
								pos: position{line: 25, col: 39, offset: 356},
								alternatives: []interface{}{
									&ruleRefExpr{
										pos:  position{line: 25, col: 39, offset: 356},
										name: "EnglishChar",
									},
									&ruleRefExpr{
										pos:  position{line: 25, col: 53, offset: 370},
										name: "UnicodeChar",
									},
									&litMatcher{
										pos:        position{line: 25, col: 67, offset: 384},
										val:        "_",
										ignoreCase: false,
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "SingleQuotedWord",
			pos:  position{line: 29, col: 1, offset: 426},
			expr: &actionExpr{
				pos: position{line: 29, col: 21, offset: 446},
				run: (*parser).callonSingleQuotedWord1,
				expr: &seqExpr{
					pos: position{line: 29, col: 21, offset: 446},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 29, col: 21, offset: 446},
							val:        "'",
							ignoreCase: false,
						},
						&labeledExpr{
							pos:   position{line: 29, col: 25, offset: 450},
							label: "v",
							expr: &ruleRefExpr{
								pos:  position{line: 29, col: 27, offset: 452},
								name: "Word",
							},
						},
						&litMatcher{
							pos:        position{line: 29, col: 32, offset: 457},
							val:        "'",
							ignoreCase: false,
						},
					},
				},
			},
		},
		{
			name: "DoubleQuotedWord",
			pos:  position{line: 33, col: 1, offset: 484},
			expr: &actionExpr{
				pos: position{line: 33, col: 21, offset: 504},
				run: (*parser).callonDoubleQuotedWord1,
				expr: &seqExpr{
					pos: position{line: 33, col: 21, offset: 504},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 33, col: 21, offset: 504},
							val:        "\"",
							ignoreCase: false,
						},
						&labeledExpr{
							pos:   position{line: 33, col: 25, offset: 508},
							label: "v",
							expr: &ruleRefExpr{
								pos:  position{line: 33, col: 27, offset: 510},
								name: "Word",
							},
						},
						&litMatcher{
							pos:        position{line: 33, col: 32, offset: 515},
							val:        "\"",
							ignoreCase: false,
						},
					},
				},
			},
		},
		{
			name: "EnglishChar",
			pos:  position{line: 37, col: 1, offset: 542},
			expr: &charClassMatcher{
				pos:        position{line: 37, col: 16, offset: 557},
				val:        "[a-zA-Z]",
				ranges:     []rune{'a', 'z', 'A', 'Z'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "UnicodeChar",
			pos:  position{line: 39, col: 1, offset: 567},
			expr: &charClassMatcher{
				pos:        position{line: 39, col: 16, offset: 582},
				val:        "[^\\u0000-\\u007F]",
				ranges:     []rune{'\x00', '\u007f'},
				ignoreCase: false,
				inverted:   true,
			},
		},
		{
			name:        "_",
			displayName: "\"whitespace\"",
			pos:         position{line: 41, col: 1, offset: 600},
			expr: &zeroOrMoreExpr{
				pos: position{line: 41, col: 19, offset: 618},
				expr: &charClassMatcher{
					pos:        position{line: 41, col: 19, offset: 618},
					val:        "[ \\n\\t\\r]",
					chars:      []rune{' ', '\n', '\t', '\r'},
					ignoreCase: false,
					inverted:   false,
				},
			},
		},
		{
			name: "EOF",
			pos:  position{line: 43, col: 1, offset: 630},
			expr: &notExpr{
				pos: position{line: 43, col: 8, offset: 637},
				expr: &anyMatcher{
					line: 43, col: 9, offset: 638,
				},
			},
		},
		{
			name: "Expr",
			pos:  position{line: 49, col: 1, offset: 659},
			expr: &actionExpr{
				pos: position{line: 49, col: 9, offset: 667},
				run: (*parser).callonExpr1,
				expr: &seqExpr{
					pos: position{line: 49, col: 9, offset: 667},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 49, col: 9, offset: 667},
							label: "first",
							expr: &choiceExpr{
								pos: position{line: 49, col: 16, offset: 674},
								alternatives: []interface{}{
									&ruleRefExpr{
										pos:  position{line: 49, col: 16, offset: 674},
										name: "Scalar",
									},
									&ruleRefExpr{
										pos:  position{line: 49, col: 25, offset: 683},
										name: "FieldSelector",
									},
								},
							},
						},
						&labeledExpr{
							pos:   position{line: 49, col: 40, offset: 698},
							label: "op",
							expr: &zeroOrOneExpr{
								pos: position{line: 49, col: 43, offset: 701},
								expr: &seqExpr{
									pos: position{line: 49, col: 44, offset: 702},
									exprs: []interface{}{
										&ruleRefExpr{
											pos:  position{line: 49, col: 44, offset: 702},
											name: "_",
										},
										&ruleRefExpr{
											pos:  position{line: 49, col: 46, offset: 704},
											name: "Operator",
										},
										&ruleRefExpr{
											pos:  position{line: 49, col: 55, offset: 713},
											name: "_",
										},
										&ruleRefExpr{
											pos:  position{line: 49, col: 57, offset: 715},
											name: "Expr",
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Scalar",
			pos:  position{line: 62, col: 1, offset: 948},
			expr: &choiceExpr{
				pos: position{line: 62, col: 12, offset: 959},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 62, col: 12, offset: 959},
						name: "StringScalar",
					},
					&ruleRefExpr{
						pos:  position{line: 62, col: 27, offset: 974},
						name: "NumericScalar",
					},
					&ruleRefExpr{
						pos:  position{line: 62, col: 43, offset: 990},
						name: "BoolScalar",
					},
				},
			},
		},
		{
			name: "StringScalar",
			pos:  position{line: 64, col: 1, offset: 1003},
			expr: &actionExpr{
				pos: position{line: 64, col: 17, offset: 1019},
				run: (*parser).callonStringScalar1,
				expr: &labeledExpr{
					pos:   position{line: 64, col: 17, offset: 1019},
					label: "val",
					expr: &choiceExpr{
						pos: position{line: 64, col: 22, offset: 1024},
						alternatives: []interface{}{
							&ruleRefExpr{
								pos:  position{line: 64, col: 22, offset: 1024},
								name: "SingleQuotedWord",
							},
							&ruleRefExpr{
								pos:  position{line: 64, col: 41, offset: 1043},
								name: "DoubleQuotedWord",
							},
						},
					},
				},
			},
		},
		{
			name: "NumericScalar",
			pos:  position{line: 68, col: 1, offset: 1144},
			expr: &actionExpr{
				pos: position{line: 68, col: 17, offset: 1162},
				run: (*parser).callonNumericScalar1,
				expr: &seqExpr{
					pos: position{line: 68, col: 17, offset: 1162},
					exprs: []interface{}{
						&zeroOrOneExpr{
							pos: position{line: 68, col: 17, offset: 1162},
							expr: &litMatcher{
								pos:        position{line: 68, col: 17, offset: 1162},
								val:        "-",
								ignoreCase: false,
							},
						},
						&ruleRefExpr{
							pos:  position{line: 68, col: 22, offset: 1167},
							name: "Integer",
						},
						&labeledExpr{
							pos:   position{line: 68, col: 30, offset: 1175},
							label: "fractional",
							expr: &zeroOrOneExpr{
								pos: position{line: 68, col: 41, offset: 1186},
								expr: &seqExpr{
									pos: position{line: 68, col: 43, offset: 1188},
									exprs: []interface{}{
										&litMatcher{
											pos:        position{line: 68, col: 43, offset: 1188},
											val:        ".",
											ignoreCase: false,
										},
										&oneOrMoreExpr{
											pos: position{line: 68, col: 47, offset: 1192},
											expr: &ruleRefExpr{
												pos:  position{line: 68, col: 47, offset: 1192},
												name: "DecimalDigit",
											},
										},
									},
								},
							},
						},
						&zeroOrOneExpr{
							pos: position{line: 68, col: 64, offset: 1209},
							expr: &ruleRefExpr{
								pos:  position{line: 68, col: 64, offset: 1209},
								name: "Exponent",
							},
						},
					},
				},
			},
		},
		{
			name: "BoolScalar",
			pos:  position{line: 86, col: 1, offset: 1666},
			expr: &actionExpr{
				pos: position{line: 86, col: 15, offset: 1680},
				run: (*parser).callonBoolScalar1,
				expr: &labeledExpr{
					pos:   position{line: 86, col: 15, offset: 1680},
					label: "v",
					expr: &choiceExpr{
						pos: position{line: 86, col: 18, offset: 1683},
						alternatives: []interface{}{
							&litMatcher{
								pos:        position{line: 86, col: 18, offset: 1683},
								val:        "true",
								ignoreCase: false,
							},
							&litMatcher{
								pos:        position{line: 86, col: 27, offset: 1692},
								val:        "TRUE",
								ignoreCase: false,
							},
							&litMatcher{
								pos:        position{line: 86, col: 36, offset: 1701},
								val:        "false",
								ignoreCase: false,
							},
							&litMatcher{
								pos:        position{line: 86, col: 46, offset: 1711},
								val:        "FALSE",
								ignoreCase: false,
							},
						},
					},
				},
			},
		},
		{
			name: "FieldSelector",
			pos:  position{line: 98, col: 1, offset: 1917},
			expr: &actionExpr{
				pos: position{line: 98, col: 18, offset: 1934},
				run: (*parser).callonFieldSelector1,
				expr: &ruleRefExpr{
					pos:  position{line: 98, col: 18, offset: 1934},
					name: "Word",
				},
			},
		},
		{
			name: "Operator",
			pos:  position{line: 106, col: 1, offset: 2010},
			expr: &ruleRefExpr{
				pos:  position{line: 106, col: 13, offset: 2022},
				name: "BinaryOperator",
			},
		},
		{
			name: "BinaryOperator",
			pos:  position{line: 108, col: 1, offset: 2038},
			expr: &ruleRefExpr{
				pos:  position{line: 108, col: 19, offset: 2056},
				name: "EqOperator",
			},
		},
		{
			name: "EqOperator",
			pos:  position{line: 110, col: 1, offset: 2068},
			expr: &actionExpr{
				pos: position{line: 110, col: 15, offset: 2082},
				run: (*parser).callonEqOperator1,
				expr: &litMatcher{
					pos:        position{line: 110, col: 15, offset: 2082},
					val:        "=",
					ignoreCase: false,
				},
			},
		},
		{
			name:        "SelectStmt",
			displayName: "\"Select statement\"",
			pos:         position{line: 120, col: 1, offset: 2203},
			expr: &actionExpr{
				pos: position{line: 120, col: 34, offset: 2236},
				run: (*parser).callonSelectStmt1,
				expr: &seqExpr{
					pos: position{line: 120, col: 34, offset: 2236},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 120, col: 34, offset: 2236},
							name: "SelectKeyWord",
						},
						&ruleRefExpr{
							pos:  position{line: 120, col: 48, offset: 2250},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 120, col: 50, offset: 2252},
							label: "from",
							expr: &ruleRefExpr{
								pos:  position{line: 120, col: 55, offset: 2257},
								name: "From",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 120, col: 60, offset: 2262},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 120, col: 62, offset: 2264},
							label: "where",
							expr: &zeroOrOneExpr{
								pos: position{line: 120, col: 68, offset: 2270},
								expr: &ruleRefExpr{
									pos:  position{line: 120, col: 68, offset: 2270},
									name: "Where",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "SelectKeyWord",
			pos:  position{line: 128, col: 1, offset: 2417},
			expr: &litMatcher{
				pos:        position{line: 128, col: 18, offset: 2434},
				val:        "select",
				ignoreCase: true,
			},
		},
		{
			name: "From",
			pos:  position{line: 130, col: 1, offset: 2445},
			expr: &actionExpr{
				pos: position{line: 130, col: 9, offset: 2453},
				run: (*parser).callonFrom1,
				expr: &seqExpr{
					pos: position{line: 130, col: 9, offset: 2453},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 130, col: 9, offset: 2453},
							name: "FromKeyWord",
						},
						&ruleRefExpr{
							pos:  position{line: 130, col: 21, offset: 2465},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 130, col: 23, offset: 2467},
							label: "tableName",
							expr: &ruleRefExpr{
								pos:  position{line: 130, col: 33, offset: 2477},
								name: "TableName",
							},
						},
					},
				},
			},
		},
		{
			name: "FromKeyWord",
			pos:  position{line: 134, col: 1, offset: 2540},
			expr: &litMatcher{
				pos:        position{line: 134, col: 16, offset: 2555},
				val:        "from",
				ignoreCase: true,
			},
		},
		{
			name: "TableName",
			pos:  position{line: 136, col: 1, offset: 2564},
			expr: &actionExpr{
				pos: position{line: 136, col: 14, offset: 2577},
				run: (*parser).callonTableName1,
				expr: &labeledExpr{
					pos:   position{line: 136, col: 14, offset: 2577},
					label: "tableName",
					expr: &ruleRefExpr{
						pos:  position{line: 136, col: 24, offset: 2587},
						name: "Word",
					},
				},
			},
		},
		{
			name: "Where",
			pos:  position{line: 141, col: 1, offset: 2639},
			expr: &actionExpr{
				pos: position{line: 141, col: 10, offset: 2648},
				run: (*parser).callonWhere1,
				expr: &seqExpr{
					pos: position{line: 141, col: 10, offset: 2648},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 141, col: 10, offset: 2648},
							name: "WhereKeyWord",
						},
						&ruleRefExpr{
							pos:  position{line: 141, col: 23, offset: 2661},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 141, col: 25, offset: 2663},
							label: "expr",
							expr: &ruleRefExpr{
								pos:  position{line: 141, col: 30, offset: 2668},
								name: "Expr",
							},
						},
					},
				},
			},
		},
		{
			name: "WhereKeyWord",
			pos:  position{line: 145, col: 1, offset: 2699},
			expr: &litMatcher{
				pos:        position{line: 145, col: 17, offset: 2715},
				val:        "where",
				ignoreCase: true,
			},
		},
	},
}

func (c *current) onInput1(stmt interface{}) (interface{}, error) {
	return stmt, nil
}

func (p *parser) callonInput1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onInput1(stack["stmt"])
}

func (c *current) onStatement1(selectStmt interface{}) (interface{}, error) {
	return selectStmt, nil
}

func (p *parser) callonStatement1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onStatement1(stack["selectStmt"])
}

func (c *current) onWord1() (interface{}, error) {
	return string(c.text), nil
}

func (p *parser) callonWord1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onWord1()
}

func (c *current) onSingleQuotedWord1(v interface{}) (interface{}, error) {
	return v, nil
}

func (p *parser) callonSingleQuotedWord1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onSingleQuotedWord1(stack["v"])
}

func (c *current) onDoubleQuotedWord1(v interface{}) (interface{}, error) {
	return v, nil
}

func (p *parser) callonDoubleQuotedWord1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onDoubleQuotedWord1(stack["v"])
}

func (c *current) onExpr1(first, op interface{}) (interface{}, error) {
	if op != nil {
		chunks := op.([]interface{})
		return chunks[1].(func(a, b query.Expr) query.Expr)(first.(query.Expr), chunks[3].(query.Expr)), nil
	}

	return first, nil
}

func (p *parser) callonExpr1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onExpr1(stack["first"], stack["op"])
}

func (c *current) onStringScalar1(val interface{}) (interface{}, error) {
	return &query.Scalar{Type: field.String, Data: []byte(val.(string))}, nil
}

func (p *parser) callonStringScalar1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onStringScalar1(stack["val"])
}

func (c *current) onNumericScalar1(fractional interface{}) (interface{}, error) {
	if fractional != nil {
		f, err := strconv.ParseFloat(string(c.text), 64)
		if err != nil {
			return nil, err
		}

		return &query.Scalar{Type: field.Float64, Value: f, Data: field.EncodeFloat64(f)}, nil
	}

	i, err := strconv.ParseInt(string(c.text), 10, 64)
	if err != nil {
		return nil, err
	}

	return &query.Scalar{Type: field.Int64, Value: i, Data: field.EncodeInt64(i)}, nil
}

func (p *parser) callonNumericScalar1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onNumericScalar1(stack["fractional"])
}

func (c *current) onBoolScalar1(v interface{}) (interface{}, error) {
	x, err := strconv.ParseBool(string(c.text))
	if err != nil {
		return nil, err
	}
	return &query.Scalar{Type: field.Bool, Value: x}, nil
}

func (p *parser) callonBoolScalar1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onBoolScalar1(stack["v"])
}

func (c *current) onFieldSelector1() (interface{}, error) {
	return query.Field(c.text), nil
}

func (p *parser) callonFieldSelector1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFieldSelector1()
}

func (c *current) onEqOperator1() (interface{}, error) {
	return func(a, b query.Expr) query.Expr {
		return query.Eqq(a, b)
	}, nil
}

func (p *parser) callonEqOperator1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onEqOperator1()
}

func (c *current) onSelectStmt1(from, where interface{}) (interface{}, error) {
	q := query.Select().From(from.(query.Table))
	if where != nil {
		q = q.Where(where.(query.Expr))
	}
	return q, nil
}

func (p *parser) callonSelectStmt1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onSelectStmt1(stack["from"], stack["where"])
}

func (c *current) onFrom1(tableName interface{}) (interface{}, error) {
	return query.Table(tableName.(string)), nil
}

func (p *parser) callonFrom1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFrom1(stack["tableName"])
}

func (c *current) onTableName1(tableName interface{}) (interface{}, error) {
	return tableName, nil
}

func (p *parser) callonTableName1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onTableName1(stack["tableName"])
}

func (c *current) onWhere1(expr interface{}) (interface{}, error) {
	return expr, nil
}

func (p *parser) callonWhere1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onWhere1(stack["expr"])
}

var (
	// errNoRule is returned when the grammar to parse has no rule.
	errNoRule = errors.New("grammar has no rule")

	// errInvalidEntrypoint is returned when the specified entrypoint rule
	// does not exit.
	errInvalidEntrypoint = errors.New("invalid entrypoint")

	// errInvalidEncoding is returned when the source is not properly
	// utf8-encoded.
	errInvalidEncoding = errors.New("invalid encoding")

	// errMaxExprCnt is used to signal that the maximum number of
	// expressions have been parsed.
	errMaxExprCnt = errors.New("max number of expresssions parsed")
)

// Option is a function that can set an option on the parser. It returns
// the previous setting as an Option.
type Option func(*parser) Option

// MaxExpressions creates an Option to stop parsing after the provided
// number of expressions have been parsed, if the value is 0 then the parser will
// parse for as many steps as needed (possibly an infinite number).
//
// The default for maxExprCnt is 0.
func MaxExpressions(maxExprCnt uint64) Option {
	return func(p *parser) Option {
		oldMaxExprCnt := p.maxExprCnt
		p.maxExprCnt = maxExprCnt
		return MaxExpressions(oldMaxExprCnt)
	}
}

// Entrypoint creates an Option to set the rule name to use as entrypoint.
// The rule name must have been specified in the -alternate-entrypoints
// if generating the parser with the -optimize-grammar flag, otherwise
// it may have been optimized out. Passing an empty string sets the
// entrypoint to the first rule in the grammar.
//
// The default is to start parsing at the first rule in the grammar.
func Entrypoint(ruleName string) Option {
	return func(p *parser) Option {
		oldEntrypoint := p.entrypoint
		p.entrypoint = ruleName
		if ruleName == "" {
			p.entrypoint = g.rules[0].name
		}
		return Entrypoint(oldEntrypoint)
	}
}

// AllowInvalidUTF8 creates an Option to allow invalid UTF-8 bytes.
// Every invalid UTF-8 byte is treated as a utf8.RuneError (U+FFFD)
// by character class matchers and is matched by the any matcher.
// The returned matched value, c.text and c.offset are NOT affected.
//
// The default is false.
func AllowInvalidUTF8(b bool) Option {
	return func(p *parser) Option {
		old := p.allowInvalidUTF8
		p.allowInvalidUTF8 = b
		return AllowInvalidUTF8(old)
	}
}

// Recover creates an Option to set the recover flag to b. When set to
// true, this causes the parser to recover from panics and convert it
// to an error. Setting it to false can be useful while debugging to
// access the full stack trace.
//
// The default is true.
func Recover(b bool) Option {
	return func(p *parser) Option {
		old := p.recover
		p.recover = b
		return Recover(old)
	}
}

// GlobalStore creates an Option to set a key to a certain value in
// the globalStore.
func GlobalStore(key string, value interface{}) Option {
	return func(p *parser) Option {
		old := p.cur.globalStore[key]
		p.cur.globalStore[key] = value
		return GlobalStore(key, old)
	}
}

// ParseFile parses the file identified by filename.
func ParseFile(filename string, opts ...Option) (i interface{}, err error) {
	f, err := os.Open(filename)
	if err != nil {
		return nil, err
	}
	defer func() {
		if closeErr := f.Close(); closeErr != nil {
			err = closeErr
		}
	}()
	return ParseReader(filename, f, opts...)
}

// ParseReader parses the data from r using filename as information in the
// error messages.
func ParseReader(filename string, r io.Reader, opts ...Option) (interface{}, error) {
	b, err := ioutil.ReadAll(r)
	if err != nil {
		return nil, err
	}

	return Parse(filename, b, opts...)
}

// Parse parses the data from b using filename as information in the
// error messages.
func Parse(filename string, b []byte, opts ...Option) (interface{}, error) {
	return newParser(filename, b, opts...).parse(g)
}

// position records a position in the text.
type position struct {
	line, col, offset int
}

func (p position) String() string {
	return strconv.Itoa(p.line) + ":" + strconv.Itoa(p.col) + " [" + strconv.Itoa(p.offset) + "]"
}

// savepoint stores all state required to go back to this point in the
// parser.
type savepoint struct {
	position
	rn rune
	w  int
}

type current struct {
	pos  position // start position of the match
	text []byte   // raw text of the match

	// globalStore is a general store for the user to store arbitrary key-value
	// pairs that they need to manage and that they do not want tied to the
	// backtracking of the parser. This is only modified by the user and never
	// rolled back by the parser. It is always up to the user to keep this in a
	// consistent state.
	globalStore storeDict
}

type storeDict map[string]interface{}

// the AST types...

type grammar struct {
	pos   position
	rules []*rule
}

type rule struct {
	pos         position
	name        string
	displayName string
	expr        interface{}
}

type choiceExpr struct {
	pos          position
	alternatives []interface{}
}

type actionExpr struct {
	pos  position
	expr interface{}
	run  func(*parser) (interface{}, error)
}

type recoveryExpr struct {
	pos          position
	expr         interface{}
	recoverExpr  interface{}
	failureLabel []string
}

type seqExpr struct {
	pos   position
	exprs []interface{}
}

type throwExpr struct {
	pos   position
	label string
}

type labeledExpr struct {
	pos   position
	label string
	expr  interface{}
}

type expr struct {
	pos  position
	expr interface{}
}

type andExpr expr
type notExpr expr
type zeroOrOneExpr expr
type zeroOrMoreExpr expr
type oneOrMoreExpr expr

type ruleRefExpr struct {
	pos  position
	name string
}

type andCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type notCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type litMatcher struct {
	pos        position
	val        string
	ignoreCase bool
}

type charClassMatcher struct {
	pos             position
	val             string
	basicLatinChars [128]bool
	chars           []rune
	ranges          []rune
	classes         []*unicode.RangeTable
	ignoreCase      bool
	inverted        bool
}

type anyMatcher position

// errList cumulates the errors found by the parser.
type errList []error

func (e *errList) add(err error) {
	*e = append(*e, err)
}

func (e errList) err() error {
	if len(e) == 0 {
		return nil
	}
	e.dedupe()
	return e
}

func (e *errList) dedupe() {
	var cleaned []error
	set := make(map[string]bool)
	for _, err := range *e {
		if msg := err.Error(); !set[msg] {
			set[msg] = true
			cleaned = append(cleaned, err)
		}
	}
	*e = cleaned
}

func (e errList) Error() string {
	switch len(e) {
	case 0:
		return ""
	case 1:
		return e[0].Error()
	default:
		var buf bytes.Buffer

		for i, err := range e {
			if i > 0 {
				buf.WriteRune('\n')
			}
			buf.WriteString(err.Error())
		}
		return buf.String()
	}
}

// parserError wraps an error with a prefix indicating the rule in which
// the error occurred. The original error is stored in the Inner field.
type parserError struct {
	Inner    error
	pos      position
	prefix   string
	expected []string
}

// Error returns the error message.
func (p *parserError) Error() string {
	return p.prefix + ": " + p.Inner.Error()
}

// newParser creates a parser with the specified input source and options.
func newParser(filename string, b []byte, opts ...Option) *parser {
	stats := Stats{
		ChoiceAltCnt: make(map[string]map[string]int),
	}

	p := &parser{
		filename: filename,
		errs:     new(errList),
		data:     b,
		pt:       savepoint{position: position{line: 1}},
		recover:  true,
		cur: current{
			globalStore: make(storeDict),
		},
		maxFailPos:      position{col: 1, line: 1},
		maxFailExpected: make([]string, 0, 20),
		Stats:           &stats,
		// start rule is rule [0] unless an alternate entrypoint is specified
		entrypoint: g.rules[0].name,
	}
	p.setOptions(opts)

	if p.maxExprCnt == 0 {
		p.maxExprCnt = math.MaxUint64
	}

	return p
}

// setOptions applies the options to the parser.
func (p *parser) setOptions(opts []Option) {
	for _, opt := range opts {
		opt(p)
	}
}

type resultTuple struct {
	v   interface{}
	b   bool
	end savepoint
}

const choiceNoMatch = -1

// Stats stores some statistics, gathered during parsing
type Stats struct {
	// ExprCnt counts the number of expressions processed during parsing
	// This value is compared to the maximum number of expressions allowed
	// (set by the MaxExpressions option).
	ExprCnt uint64

	// ChoiceAltCnt is used to count for each ordered choice expression,
	// which alternative is used how may times.
	// These numbers allow to optimize the order of the ordered choice expression
	// to increase the performance of the parser
	//
	// The outer key of ChoiceAltCnt is composed of the name of the rule as well
	// as the line and the column of the ordered choice.
	// The inner key of ChoiceAltCnt is the number (one-based) of the matching alternative.
	// For each alternative the number of matches are counted. If an ordered choice does not
	// match, a special counter is incremented. The name of this counter is set with
	// the parser option Statistics.
	// For an alternative to be included in ChoiceAltCnt, it has to match at least once.
	ChoiceAltCnt map[string]map[string]int
}

type parser struct {
	filename string
	pt       savepoint
	cur      current

	data []byte
	errs *errList

	depth   int
	recover bool

	// rules table, maps the rule identifier to the rule node
	rules map[string]*rule
	// variables stack, map of label to value
	vstack []map[string]interface{}
	// rule stack, allows identification of the current rule in errors
	rstack []*rule

	// parse fail
	maxFailPos            position
	maxFailExpected       []string
	maxFailInvertExpected bool

	// max number of expressions to be parsed
	maxExprCnt uint64
	// entrypoint for the parser
	entrypoint string

	allowInvalidUTF8 bool

	*Stats

	choiceNoMatch string
	// recovery expression stack, keeps track of the currently available recovery expression, these are traversed in reverse
	recoveryStack []map[string]interface{}
}

// push a variable set on the vstack.
func (p *parser) pushV() {
	if cap(p.vstack) == len(p.vstack) {
		// create new empty slot in the stack
		p.vstack = append(p.vstack, nil)
	} else {
		// slice to 1 more
		p.vstack = p.vstack[:len(p.vstack)+1]
	}

	// get the last args set
	m := p.vstack[len(p.vstack)-1]
	if m != nil && len(m) == 0 {
		// empty map, all good
		return
	}

	m = make(map[string]interface{})
	p.vstack[len(p.vstack)-1] = m
}

// pop a variable set from the vstack.
func (p *parser) popV() {
	// if the map is not empty, clear it
	m := p.vstack[len(p.vstack)-1]
	if len(m) > 0 {
		// GC that map
		p.vstack[len(p.vstack)-1] = nil
	}
	p.vstack = p.vstack[:len(p.vstack)-1]
}

// push a recovery expression with its labels to the recoveryStack
func (p *parser) pushRecovery(labels []string, expr interface{}) {
	if cap(p.recoveryStack) == len(p.recoveryStack) {
		// create new empty slot in the stack
		p.recoveryStack = append(p.recoveryStack, nil)
	} else {
		// slice to 1 more
		p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)+1]
	}

	m := make(map[string]interface{}, len(labels))
	for _, fl := range labels {
		m[fl] = expr
	}
	p.recoveryStack[len(p.recoveryStack)-1] = m
}

// pop a recovery expression from the recoveryStack
func (p *parser) popRecovery() {
	// GC that map
	p.recoveryStack[len(p.recoveryStack)-1] = nil

	p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)-1]
}

func (p *parser) addErr(err error) {
	p.addErrAt(err, p.pt.position, []string{})
}

func (p *parser) addErrAt(err error, pos position, expected []string) {
	var buf bytes.Buffer
	if p.filename != "" {
		buf.WriteString(p.filename)
	}
	if buf.Len() > 0 {
		buf.WriteString(":")
	}
	buf.WriteString(fmt.Sprintf("%d:%d (%d)", pos.line, pos.col, pos.offset))
	if len(p.rstack) > 0 {
		if buf.Len() > 0 {
			buf.WriteString(": ")
		}
		rule := p.rstack[len(p.rstack)-1]
		if rule.displayName != "" {
			buf.WriteString("rule " + rule.displayName)
		} else {
			buf.WriteString("rule " + rule.name)
		}
	}
	pe := &parserError{Inner: err, pos: pos, prefix: buf.String(), expected: expected}
	p.errs.add(pe)
}

func (p *parser) failAt(fail bool, pos position, want string) {
	// process fail if parsing fails and not inverted or parsing succeeds and invert is set
	if fail == p.maxFailInvertExpected {
		if pos.offset < p.maxFailPos.offset {
			return
		}

		if pos.offset > p.maxFailPos.offset {
			p.maxFailPos = pos
			p.maxFailExpected = p.maxFailExpected[:0]
		}

		if p.maxFailInvertExpected {
			want = "!" + want
		}
		p.maxFailExpected = append(p.maxFailExpected, want)
	}
}

// read advances the parser to the next rune.
func (p *parser) read() {
	p.pt.offset += p.pt.w
	rn, n := utf8.DecodeRune(p.data[p.pt.offset:])
	p.pt.rn = rn
	p.pt.w = n
	p.pt.col++
	if rn == '\n' {
		p.pt.line++
		p.pt.col = 0
	}

	if rn == utf8.RuneError && n == 1 { // see utf8.DecodeRune
		if !p.allowInvalidUTF8 {
			p.addErr(errInvalidEncoding)
		}
	}
}

// restore parser position to the savepoint pt.
func (p *parser) restore(pt savepoint) {
	if pt.offset == p.pt.offset {
		return
	}
	p.pt = pt
}

// get the slice of bytes from the savepoint start to the current position.
func (p *parser) sliceFrom(start savepoint) []byte {
	return p.data[start.position.offset:p.pt.position.offset]
}

func (p *parser) buildRulesTable(g *grammar) {
	p.rules = make(map[string]*rule, len(g.rules))
	for _, r := range g.rules {
		p.rules[r.name] = r
	}
}

func (p *parser) parse(g *grammar) (val interface{}, err error) {
	if len(g.rules) == 0 {
		p.addErr(errNoRule)
		return nil, p.errs.err()
	}

	// TODO : not super critical but this could be generated
	p.buildRulesTable(g)

	if p.recover {
		// panic can be used in action code to stop parsing immediately
		// and return the panic as an error.
		defer func() {
			if e := recover(); e != nil {
				val = nil
				switch e := e.(type) {
				case error:
					p.addErr(e)
				default:
					p.addErr(fmt.Errorf("%v", e))
				}
				err = p.errs.err()
			}
		}()
	}

	startRule, ok := p.rules[p.entrypoint]
	if !ok {
		p.addErr(errInvalidEntrypoint)
		return nil, p.errs.err()
	}

	p.read() // advance to first rune
	val, ok = p.parseRule(startRule)
	if !ok {
		if len(*p.errs) == 0 {
			// If parsing fails, but no errors have been recorded, the expected values
			// for the farthest parser position are returned as error.
			maxFailExpectedMap := make(map[string]struct{}, len(p.maxFailExpected))
			for _, v := range p.maxFailExpected {
				maxFailExpectedMap[v] = struct{}{}
			}
			expected := make([]string, 0, len(maxFailExpectedMap))
			eof := false
			if _, ok := maxFailExpectedMap["!."]; ok {
				delete(maxFailExpectedMap, "!.")
				eof = true
			}
			for k := range maxFailExpectedMap {
				expected = append(expected, k)
			}
			sort.Strings(expected)
			if eof {
				expected = append(expected, "EOF")
			}
			p.addErrAt(errors.New("no match found, expected: "+listJoin(expected, ", ", "or")), p.maxFailPos, expected)
		}

		return nil, p.errs.err()
	}
	return val, p.errs.err()
}

func listJoin(list []string, sep string, lastSep string) string {
	switch len(list) {
	case 0:
		return ""
	case 1:
		return list[0]
	default:
		return strings.Join(list[:len(list)-1], sep) + " " + lastSep + " " + list[len(list)-1]
	}
}

func (p *parser) parseRule(rule *rule) (interface{}, bool) {
	p.rstack = append(p.rstack, rule)
	p.pushV()
	val, ok := p.parseExpr(rule.expr)
	p.popV()
	p.rstack = p.rstack[:len(p.rstack)-1]
	return val, ok
}

func (p *parser) parseExpr(expr interface{}) (interface{}, bool) {

	p.ExprCnt++
	if p.ExprCnt > p.maxExprCnt {
		panic(errMaxExprCnt)
	}

	var val interface{}
	var ok bool
	switch expr := expr.(type) {
	case *actionExpr:
		val, ok = p.parseActionExpr(expr)
	case *andCodeExpr:
		val, ok = p.parseAndCodeExpr(expr)
	case *andExpr:
		val, ok = p.parseAndExpr(expr)
	case *anyMatcher:
		val, ok = p.parseAnyMatcher(expr)
	case *charClassMatcher:
		val, ok = p.parseCharClassMatcher(expr)
	case *choiceExpr:
		val, ok = p.parseChoiceExpr(expr)
	case *labeledExpr:
		val, ok = p.parseLabeledExpr(expr)
	case *litMatcher:
		val, ok = p.parseLitMatcher(expr)
	case *notCodeExpr:
		val, ok = p.parseNotCodeExpr(expr)
	case *notExpr:
		val, ok = p.parseNotExpr(expr)
	case *oneOrMoreExpr:
		val, ok = p.parseOneOrMoreExpr(expr)
	case *recoveryExpr:
		val, ok = p.parseRecoveryExpr(expr)
	case *ruleRefExpr:
		val, ok = p.parseRuleRefExpr(expr)
	case *seqExpr:
		val, ok = p.parseSeqExpr(expr)
	case *throwExpr:
		val, ok = p.parseThrowExpr(expr)
	case *zeroOrMoreExpr:
		val, ok = p.parseZeroOrMoreExpr(expr)
	case *zeroOrOneExpr:
		val, ok = p.parseZeroOrOneExpr(expr)
	default:
		panic(fmt.Sprintf("unknown expression type %T", expr))
	}
	return val, ok
}

func (p *parser) parseActionExpr(act *actionExpr) (interface{}, bool) {
	start := p.pt
	val, ok := p.parseExpr(act.expr)
	if ok {
		p.cur.pos = start.position
		p.cur.text = p.sliceFrom(start)
		actVal, err := act.run(p)
		if err != nil {
			p.addErrAt(err, start.position, []string{})
		}

		val = actVal
	}
	return val, ok
}

func (p *parser) parseAndCodeExpr(and *andCodeExpr) (interface{}, bool) {

	ok, err := and.run(p)
	if err != nil {
		p.addErr(err)
	}

	return nil, ok
}

func (p *parser) parseAndExpr(and *andExpr) (interface{}, bool) {
	pt := p.pt
	p.pushV()
	_, ok := p.parseExpr(and.expr)
	p.popV()
	p.restore(pt)

	return nil, ok
}

func (p *parser) parseAnyMatcher(any *anyMatcher) (interface{}, bool) {
	if p.pt.rn == utf8.RuneError && p.pt.w == 0 {
		// EOF - see utf8.DecodeRune
		p.failAt(false, p.pt.position, ".")
		return nil, false
	}
	start := p.pt
	p.read()
	p.failAt(true, start.position, ".")
	return p.sliceFrom(start), true
}

func (p *parser) parseCharClassMatcher(chr *charClassMatcher) (interface{}, bool) {
	cur := p.pt.rn
	start := p.pt

	// can't match EOF
	if cur == utf8.RuneError && p.pt.w == 0 { // see utf8.DecodeRune
		p.failAt(false, start.position, chr.val)
		return nil, false
	}

	if chr.ignoreCase {
		cur = unicode.ToLower(cur)
	}

	// try to match in the list of available chars
	for _, rn := range chr.chars {
		if rn == cur {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of ranges
	for i := 0; i < len(chr.ranges); i += 2 {
		if cur >= chr.ranges[i] && cur <= chr.ranges[i+1] {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of Unicode classes
	for _, cl := range chr.classes {
		if unicode.Is(cl, cur) {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	if chr.inverted {
		p.read()
		p.failAt(true, start.position, chr.val)
		return p.sliceFrom(start), true
	}
	p.failAt(false, start.position, chr.val)
	return nil, false
}

func (p *parser) parseChoiceExpr(ch *choiceExpr) (interface{}, bool) {
	for altI, alt := range ch.alternatives {
		// dummy assignment to prevent compile error if optimized
		_ = altI

		p.pushV()
		val, ok := p.parseExpr(alt)
		p.popV()
		if ok {
			return val, ok
		}
	}
	return nil, false
}

func (p *parser) parseLabeledExpr(lab *labeledExpr) (interface{}, bool) {
	p.pushV()
	val, ok := p.parseExpr(lab.expr)
	p.popV()
	if ok && lab.label != "" {
		m := p.vstack[len(p.vstack)-1]
		m[lab.label] = val
	}
	return val, ok
}

func (p *parser) parseLitMatcher(lit *litMatcher) (interface{}, bool) {
	ignoreCase := ""
	if lit.ignoreCase {
		ignoreCase = "i"
	}
	val := string(strconv.AppendQuote([]byte{}, lit.val)) + ignoreCase // wrap 'lit.val' with double quotes
	start := p.pt
	for _, want := range lit.val {
		cur := p.pt.rn
		if lit.ignoreCase {
			cur = unicode.ToLower(cur)
		}
		if cur != want {
			p.failAt(false, start.position, val)
			p.restore(start)
			return nil, false
		}
		p.read()
	}
	p.failAt(true, start.position, val)
	return p.sliceFrom(start), true
}

func (p *parser) parseNotCodeExpr(not *notCodeExpr) (interface{}, bool) {
	ok, err := not.run(p)
	if err != nil {
		p.addErr(err)
	}

	return nil, !ok
}

func (p *parser) parseNotExpr(not *notExpr) (interface{}, bool) {
	pt := p.pt
	p.pushV()
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	_, ok := p.parseExpr(not.expr)
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	p.popV()
	p.restore(pt)

	return nil, !ok
}

func (p *parser) parseOneOrMoreExpr(expr *oneOrMoreExpr) (interface{}, bool) {
	var vals []interface{}

	for {
		p.pushV()
		val, ok := p.parseExpr(expr.expr)
		p.popV()
		if !ok {
			if len(vals) == 0 {
				// did not match once, no match
				return nil, false
			}
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseRecoveryExpr(recover *recoveryExpr) (interface{}, bool) {

	p.pushRecovery(recover.failureLabel, recover.recoverExpr)
	val, ok := p.parseExpr(recover.expr)
	p.popRecovery()

	return val, ok
}

func (p *parser) parseRuleRefExpr(ref *ruleRefExpr) (interface{}, bool) {
	if ref.name == "" {
		panic(fmt.Sprintf("%s: invalid rule: missing name", ref.pos))
	}

	rule := p.rules[ref.name]
	if rule == nil {
		p.addErr(fmt.Errorf("undefined rule: %s", ref.name))
		return nil, false
	}
	return p.parseRule(rule)
}

func (p *parser) parseSeqExpr(seq *seqExpr) (interface{}, bool) {
	vals := make([]interface{}, 0, len(seq.exprs))

	pt := p.pt
	for _, expr := range seq.exprs {
		val, ok := p.parseExpr(expr)
		if !ok {
			p.restore(pt)
			return nil, false
		}
		vals = append(vals, val)
	}
	return vals, true
}

func (p *parser) parseThrowExpr(expr *throwExpr) (interface{}, bool) {

	for i := len(p.recoveryStack) - 1; i >= 0; i-- {
		if recoverExpr, ok := p.recoveryStack[i][expr.label]; ok {
			if val, ok := p.parseExpr(recoverExpr); ok {
				return val, ok
			}
		}
	}

	return nil, false
}

func (p *parser) parseZeroOrMoreExpr(expr *zeroOrMoreExpr) (interface{}, bool) {
	var vals []interface{}

	for {
		p.pushV()
		val, ok := p.parseExpr(expr.expr)
		p.popV()
		if !ok {
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseZeroOrOneExpr(expr *zeroOrOneExpr) (interface{}, bool) {
	p.pushV()
	val, _ := p.parseExpr(expr.expr)
	p.popV()
	// whether it matched or not, consider it a match
	return val, true
}
