// Code generated by "stringer -type=Operation"; DO NOT EDIT.

package planner

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Input-0]
	_ = x[Selection-1]
	_ = x[Projection-2]
	_ = x[Rename-3]
	_ = x[Deletion-4]
	_ = x[Replacement-5]
	_ = x[Limit-6]
	_ = x[Skip-7]
	_ = x[Sort-8]
	_ = x[Set-9]
	_ = x[Unset-10]
}

const _Operation_name = "InputSelectionProjectionRenameDeletionReplacementLimitSkipSortSetUnset"

var _Operation_index = [...]uint8{0, 5, 14, 24, 30, 38, 49, 54, 58, 62, 65, 70}

func (i Operation) String() string {
	if i < 0 || i >= Operation(len(_Operation_index)-1) {
		return "Operation(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Operation_name[_Operation_index[i]:_Operation_index[i+1]]
}
